controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ChangePasswordForm;
use app\models\PassForm;
use app\models\UploadForm;
use app\models\User;
use app\models\EntryForm;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $diff = date_diff( new \DateTime(), new \DateTime($model->getUser()->getLastReset()));
            if( $diff->format('%a') >= yii::$app->params['passResetTime']){
                return $this->redirect('site/change-password');
            }
            return $this->goBack();
        }

        if (Yii::$app->user->isGuest) {
            return $this->render('login', ['model' => $model]);
        }

        $query = User::find();

        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count(),
        ]);
        $users = $query->orderBy('email')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index',[
            'users' => $users,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionChangePassword()
    {
        if (Yii::$app->user->isGuest){
            return $this->redirect('index');
        }
        $id = Yii::$app->user->id;

        $model = new ChangePasswordForm($id);

        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->changePassword() ){
            Yii::$app->session->setFlash('success',"Hasło zostało zmienione");
            return $this->redirect('index');
        }

        return $this->render('pass',[
            'model' => $model,
        ]);
    }
    public function actionUploadUsers()
    {
        if (Yii::$app->user->isGuest){
            return $this->redirect('index');
        }

        $model = new UploadForm();

        if (yii::$app->request->isPost){
            $model->xlsFile = UploadedFile::getInstance($model, 'xlsFile');
            $file = $model->upload();
            if($file){
                $excel = \PHPExcel_IOFactory::load('uploads/'.$file);
                $excelArray = $excel->getActiveSheet()->toArray(null, true, true , true);
                $messages = [];
                $i = 0;                                                     //licznik ilosci dodanych uzytkownikow
                foreach($excelArray as $row) {
                    $randomPassword = yii::$app->security->generateRandomString(8);
                    $hash = yii::$app->security->generatePasswordHash($randomPassword);
                    $user = new User();
                    $user->name = $row['A'];
                    $user->surname = $row['B'];
                    $user->email = $row['C'];
                    $user->password = $hash;

                    $user->last_reset = date('Y-m-d');
                    if ($user->save()) {
                        $messages[] = yii::$app->mailer->compose('greeting.php', [
                            'name' => $user->name,
                            'surname' => $user->surname,
                            'password' => $randomPassword,
                            'email' => $user->email,
                        ])
                            ->setFrom(yii::$app->params['adminEmail'])
                            ->setTo($user->email)
                            ->setSubject('Witaj w naszej aplikacji');
                        $i++;
                    }
                }
                if(!empty($messages)){
                    yii::$app->mailer->sendMultiple($messages);
                    yii::$app->session->setFlash('success','Dodano '.$i.' użytkowników');
                }                    else{
                    yii::$app->session->setFlash('danger','W pliku nie znaleziono poprawnych adresów email');
                }
                unlink('uploads/'.$file);
                //return $this->redirect('index');
                }
        }
        return $this->render('upload',[
           'model' => $model,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    if(Yii::$app->user->identity){
        NavBar::begin([
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'Zmień hasło', 'url' => ['/site/change-password']],
                ['label' => 'Dodaj użytkowników', 'url' => ['/site/upload-users']],
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->email . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ],
        ]);
        NavBar::end();
    }
    ?>

    <div class="container">
        <?php
            foreach (yii::$app->session->getAllFlashes() as $key => $message){
                echo '<div class="alert alert-' . $key . '">' . $message . "</div>\n";
            }?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Radek Popek <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>